# Generated by Django 6.1.1 on 2026-10-07 06:57
#
# TASK-BACK-CRM-01: `appointment`. Las dos `RunPython` del final agregan los
# `EXCLUDE USING gist` de solapamiento, que Django no puede expresar en
# `Meta.constraints`. Solo corren en PostgreSQL, donde la suite no llega: en
# SQLite la misma regla aplican `services._overlapping_appointments()` y el
# índice parcial `appointment_property_slot_unique`, igual que en
# `properties.0002` con su `EXCLUDE`.
#
# Hay dos restricciones porque la regla de negocio también es doble
# (`docs/database/indexes-and-queries.md` §2.3 para la propiedad,
# `docs/database/data-model.md` §3.1 y `docs/api/README.md` para el agente):
# una propiedad no puede tener dos visitas a la vez y un agente no puede
# atender dos visitas a la vez. Ambas usan el mismo predicado parcial que
# `Appointment.ACTIVE_STATUSES`, para que lo que la base bloquea sea
# exactamente lo que `available-slots` ya daba por ocupado.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

NO_OVERLAP_SQL = """
    CREATE EXTENSION IF NOT EXISTS btree_gist;

    ALTER TABLE appointment
      ADD CONSTRAINT appointment_property_no_overlap
      EXCLUDE USING gist (
        property_id WITH =,
        tstzrange(scheduled_at, end_at, '[)') WITH &&
      ) WHERE (status IN ('PENDING', 'CONFIRMED', 'RESCHEDULED'));

    ALTER TABLE appointment
      ADD CONSTRAINT appointment_agent_no_overlap
      EXCLUDE USING gist (
        agent_id WITH =,
        tstzrange(scheduled_at, end_at, '[)') WITH &&
      ) WHERE (status IN ('PENDING', 'CONFIRMED', 'RESCHEDULED'));
"""

DROP_NO_OVERLAP_SQL = """
    ALTER TABLE appointment DROP CONSTRAINT IF EXISTS appointment_property_no_overlap;
    ALTER TABLE appointment DROP CONSTRAINT IF EXISTS appointment_agent_no_overlap;
"""


def add_no_overlap(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for statement in NO_OVERLAP_SQL.split(";"):
        if statement.strip():
            schema_editor.execute(statement)


def drop_no_overlap(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for statement in DROP_NO_OVERLAP_SQL.split(";"):
        if statement.strip():
            schema_editor.execute(statement)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.SmallIntegerField(default=45)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('RESCHEDULED', 'Reprogramada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No asistió')], default='PENDING', max_length=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reschedule_count', models.IntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('CLIENT_WEB', 'Web del cliente'), ('AGENT', 'Panel del agente'), ('ADMIN', 'Panel del administrador'), ('AI_CHAT', 'Chat con IA')], default='CLIENT_WEB', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_agent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_client', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='properties.property')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rescheduled_into', to='appointments.appointment')),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='properties.propertyschedule')),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ('scheduled_at',),
                'indexes': [models.Index(fields=['client', '-scheduled_at'], name='appointment_client_idx'), models.Index(fields=['agent', 'scheduled_at'], name='appointment_agent_idx'), models.Index(fields=['status', 'scheduled_at'], name='appointment_status_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW'])), name='appointment_status_check'), models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 15), ('duration_minutes__lte', 480)), name='appointment_duration_range'), models.CheckConstraint(condition=models.Q(('reschedule_count__gte', 0)), name='appointment_reschedule_count_positive'), models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'CONFIRMED', 'RESCHEDULED'))), fields=('property', 'scheduled_at'), name='appointment_property_slot_unique')],
            },
        ),
        migrations.RunPython(add_no_overlap, drop_no_overlap),
    ]
