# Generated by Django 6.1.1 on 2026-10-03 21:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ubigeo', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('department', models.CharField(default='Lima', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ubigeo__regex', '^[0-9]{6}$')), name='district_ubigeo_format')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('mode', models.CharField(choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler')], max_length=12)),
                ('property_type', models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('CASA', 'Casa'), ('TERRENO', 'Terreno'), ('OFICINA', 'Oficina')], max_length=20)),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('ALQUILADO', 'Alquilado'), ('VENDIDO', 'Vendido'), ('SUSPENDIDO', 'Suspendido')], default='DISPONIBLE', max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_built', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.SmallIntegerField(blank=True, null=True)),
                ('parking_spaces', models.SmallIntegerField(default=0)),
                ('maintenance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accepts_pets', models.BooleanField(default=False)),
                ('accepts_children', models.BooleanField(default=False)),
                ('is_negotiable', models.BooleanField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('exterior_url', models.URLField(blank=True, max_length=500, null=True)),
                ('floorplan_url', models.URLField(blank=True, max_length=500, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('owner_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.district')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_representative', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='properties.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'status', 'property_type', '-created_at'], name='property_catalog_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='property_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['PEN', 'USD'])), name='property_currency_check'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['VENTA', 'ALQUILER'])), name='property_mode_check'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('property_type__in', ['DEPARTAMENTO', 'CASA', 'TERRENO', 'OFICINA'])), name='property_type_check'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DISPONIBLE', 'RESERVADO', 'ALQUILADO', 'VENDIDO', 'SUSPENDIDO'])), name='property_status_check'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('parking_spaces__gte', 0)), name='property_parking_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_fee__isnull', True), ('maintenance_fee__gte', 0), _connector='OR'), name='property_maintenance_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('area_total__isnull', True), ('area_total__gte', 0), _connector='OR'), name='property_area_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('area_built__isnull', True), ('area_built__gte', 0), _connector='OR'), name='property_area_built_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__isnull', True), ('bedrooms__gte', 0), _connector='OR'), name='property_bedrooms_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__isnull', True), ('bathrooms__gte', 0), _connector='OR'), name='property_bathrooms_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__isnull', True), models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 1)), _connector='OR'), name='property_commission_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('status', 'SUSPENDIDO'), _negated=True), name='property_suspended_is_inactive'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(fields=('property', 'storage_key'), name='property_image_storage_unique'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('property',), name='property_image_single_cover'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.CheckConstraint(condition=models.Q(('width__isnull', True), ('width__gt', 0), _connector='OR'), name='property_image_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.CheckConstraint(condition=models.Q(('height__isnull', True), ('height__gt', 0), _connector='OR'), name='property_image_height_positive'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='property_image_sort_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='propertyowner',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('property', 'document_number'), name='property_owner_document_unique'),
        ),
    ]
