# Generated by Django 6.1.1 on 2026-10-05 17:14
#
# TASK-BACK-PROP-04: `property_schedule_slot` y `property_status_change`.
#
# La operación `RunPython` del final agrega el `EXCLUDE USING gist` que Django
# no puede expresar en `Meta.constraints`. Solo corre en PostgreSQL: la suite
# usa SQLite, donde la misma regla la aplican `PropertySchedule.clean()` y
# `services.validate_day()`.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

NO_OVERLAP_SQL = """
    ALTER TABLE property_schedule_slot
      ADD CONSTRAINT property_schedule_slot_no_overlap
      EXCLUDE USING gist (
        property_id WITH =,
        tsrange(start_time, end_time, '[)') WITH &&
      ) WHERE (is_active)
"""

DROP_NO_OVERLAP_SQL = """
    ALTER TABLE property_schedule_slot
      DROP CONSTRAINT IF EXISTS property_schedule_slot_no_overlap
"""


def add_no_overlap(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    pass


def drop_no_overlap(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(DROP_NO_OVERLAP_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='properties.property')),
            ],
            options={
                'db_table': 'property_schedule_slot',
                'ordering': ('weekday', 'start_time'),
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='schedule_weekday_range'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start'), models.UniqueConstraint(fields=('property', 'weekday', 'start_time'), name='schedule_unique_start_per_weekday'), models.UniqueConstraint(fields=('property', 'weekday', 'start_time', 'end_time'), name='schedule_unique_range_per_weekday')],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('ALQUILADO', 'Alquilado'), ('VENDIDO', 'Vendido'), ('SUSPENDIDO', 'Suspendido')], max_length=15, null=True)),
                ('new_status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('ALQUILADO', 'Alquilado'), ('VENDIDO', 'Vendido'), ('SUSPENDIDO', 'Suspendido')], max_length=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_status_changes', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='properties.property')),
            ],
            options={
                'db_table': 'property_status_change',
                'ordering': ('-changed_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('previous_status', models.F('new_status')), _negated=True), name='status_change_differs_from_previous'), models.CheckConstraint(condition=models.Q(('new_status__in', ['DISPONIBLE', 'RESERVADO', 'ALQUILADO', 'VENDIDO', 'SUSPENDIDO'])), name='status_change_new_status_check')],
            },
        ),
        migrations.RunPython(add_no_overlap, drop_no_overlap),
    ]
